### ISSUE TITLE
Stuck on registering listeners

### ISSUE THREAD

**Issue by nospoon** [ratchetphp/Pawl#103]
When calling the `on($event, $callback)` method on the connection, it gets stuck and never progresses to the next code block.

For example:
```
connect($url)->then(function (WebSocket $connection) use ($callback) {
    $this->webSocket = $connection;
    var_dump('test1');
    $this->webSocket->on('open', function (WebSocketMessage $message) {
        // do something;
     });
    var_dump('test2');
    $this->webSocket->on('message', function (WebSocketMessage $message) {
        // do something else;
    });

    call_user_func($callback, $connection);
});
```
In the above code, I expect both "test1" and "test2" debug messages, but only "test1" is ever fired, hence the `$callback` is also never triggered.

**Comment by envatic** [comment]
there is no `open` event it seems
