### ISSUE TITLE
Send binary data in ratchet 0.3.6

### ISSUE THREAD

**Issue by aks2193** [ratchetphp/Pawl#105]
Hey guys,

I want to send compressed string as binary format in ratchet 0.3.6
As per my understand we directly have a method for this in 0.4.
Is there anything I can apply in 0.3.6 to solve this.
Thanks for the help.
@cboden

**Comment by cboden** [comment]
Ratchet/v0.3 was released in 2013 so my memory is super foggy but I don't think binary messages were supported back then. The v0.4 release notes include "Binary messages now supported" to further add to my recollection. 

I poked around the code and didn't see anything restricting binary messages in v0.3, so I think `onMessage` will just have the raw binary data if you were to send a binary message to it, but again, I can't recall for certain. 🤷‍♀️
