### ISSUE TITLE
Drain event support

### ISSUE THREAD

**Issue by Ekstazi** [ratchetphp/Pawl#108]
Currently websocket client doesn't support tcp/ip backpressure  I want to fix it.

**Comment by clue** [comment]
@Ekstazi Thanks for bring this up, this is an interesting one :+1: 

Do you have any details how this is handled in other WebSocket implementations? It looks like browsers and many others implementations don't expose this either. The [`bufferedAmount`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/bufferedAmount) property can give *some* insight, but it doesn't provide a notification mechanism, there only appears to be a browser-specific limit causing the connection to fail if the buffer keeps growing.

I'm not sure which API this project aims to follow, but if it were to follow ReactPHP's `DuplexStreamInterface`, I would agree that exposing the `drain` event makes perfect sense. If it aims to follow the browser API, IMHO exposing `drain` and also #91 should not be done.

**Comment by Ekstazi** [comment]
I think we must follow reactphp way.  `amphp/websocket-client`uses tcp/ip backpressure. Nodejs ws streams also use drain [event](https://github.com/websockets/ws/blob/master/lib/websocket.js#L156 ). 
Without that the client can ddos server.

**Comment by Ekstazi** [comment]
Also i did some expirements with ratchetphp and novnc. After some buffered amount in exceeded, the browser paused websocket so it doesn't receive new data and tcp backpressure used.

**Comment by clue** [comment]
> Without that the client can ddos server.

That's not something backpressure / drain support in the client addresses. The drain event only operates on the client side buffer, i.e. it allows the client to know when to send more data. If the client keeps sending without respecting the buffer, it will eventually run out of memory (i.e. it could only DoS itself).

> Also i did some expirements with ratchetphp and novnc. After some buffered amount in exceeded, the browser paused websocket so it doesn't receive new data and tcp backpressure used.

The `drain` event only operates on the *sending* side and has no effect on how data is *received*. The underlying socket connection takes care of handling backpressure on the socket level and ensures both sides receive data as fast as the connection bandwidth allows.

**Comment by Ekstazi** [comment]
You are right. I know about that. Sorry for my bad english. That i try to explain is:
* if sending buffer is full then client can't respond to ping at acceptable time and connection can be closed by server.
* if client send data without respecting drain event then it ddos itself and connection closed because of pong delay.
So i think the right way is to control sending buffer on client side. So client can ensure that server receive data as fast as the connection bandwidth allows.

**Comment by cboden** [comment]
Can you post your code examples and results of your tests with and without your changes please? I'm happy for contributions and to merge pull requests, but I'd prefer evidence to support the changes.

**Comment by cboden** [comment]
merged #109
