### ISSUE TITLE
Documented method __toString in Message class, do not exist

### ISSUE THREAD

**Issue by carliedu** [ratchetphp/Pawl#116]
In README.md is written that, most times we want to access the data received, using the method __toString from primary class Message.
There, topic about Message class, it says: 
"This is the object received from a WebSocket server. It has a __toString method which is how most times you will want to access the data received. If you need to do binary messaging you will most likely need to use methods on the object."
This method not exist.

**Comment by cboden** [comment]
[Here](https://github.com/ratchetphp/RFC6455/blob/master/src/Messaging/Message.php#L100) is the method definition.

**Comment by carliedu** [comment]
Thanks. I was looking in the wrong place.
