### ISSUE TITLE
No timeout connecting to a frozen websocket server

### ISSUE THREAD

**Issue by jab11** [ratchetphp/Pawl#117]
1. I'm using pawl@0.3.5 to connect to a ratchet websocket server
2. for whatever reason sometimes the server hangs either in some infinite cycle or a database query
3. pawl opens a connection to the hung server, tcp connection succeeds so the TimeoutConnector succeeds, but never receives header data, so the $futureWsConn promise in __invoke() never resolves

How can I catch this event ? It would be nice if Connector simply rejected the promise if websocket headers are not received within the default timeout window.

For now I'm using a Timer\timeout to kill the EventLoop but it's not a great solution.

**Comment by cboden** [comment]
Can you provide a demo server+client code to reproduce this?
