### ISSUE TITLE
Little change please

### ISSUE THREAD

**Issue by lcwong82** [ratchetphp/Pawl#118]
from

https://github.com/ratchetphp/Pawl

at example

```
$connector('ws://127.0.0.1:9000', ['protocol1', 'subprotocol2'], ['Origin' => 'http://localhost'])
    ->then(function(Ratchet\Client\WebSocket $conn) {
```

Please add  **\Ratchet\Client\WebSocket $conn**
when paste it somewhere with namespace, which will cause an unknown error, it will get stuck there without going to $conn->send('Hello World!');

**Comment by cboden** [comment]
Done. Thank you!
