### ISSUE TITLE
Use RatchetPHP for pushing data only and get connected with PHP client.

### ISSUE THREAD

**Issue by joaquin-gs** [ratchetphp/Pawl#120]
Hi guys!

Is there a way to get connected to the Websocket Server without using a loop in the PHP client? I am playing a bit with Ratchet server and Pawl but it seems the Pawl loop blocks my javascript client.
What I need to do is to send, from PHP, a data/message to the javascript clients to notify/update web content with JS.
I would like to get connected to the WS Server, send the message to a JS client and disconnect. That's it!

Any clue on this, please?

**Comment by mohamedryan** [comment]
I faced the same problem and fixed it by closing the connection after sending the data

example:

```
public function sendWsocketMsg($data)
{
    \Ratchet\Client\connect("wss://yourWSLinkWithPort")->then(function($conn) use($data) {
        try {
            $conn->send(json_encode($data));
        } catch (\Exception $e) {
            echo "Error send data from PHP code, msg: {$e->getMessage()}\n";
        }
        finally{
            // this is a must to not make the system hang.
            $conn->close(); 
        }
    }, function ($e) {
        echo "Could not connect: {$e->getMessage()}\n";
    });
}
```
