### ISSUE TITLE
How to subscribe to given events?

### ISSUE THREAD

**Issue by typoworx-de** [ratchetphp/Pawl#122]
How can I subscribe to given events provided by websocket server I'm connected to?

Is this rather the same then using this method?
```php
    \Ratchet\Client\connect('wss://echo.websocket.org:443')->then(function($conn) {
        $conn->on('custom-event', function($msg) use ($conn) {
            echo "Received 'custom-event': {$msg}\n";            
            $conn->close();
        });
```

**Comment by clue** [comment]
@typoworx-de Thanks for bringing this up!

The `WebSocket` object always emits a `message` event as per the documentation:

```php
\Ratchet\Client\connect('wss://echo.websocket.org:443')->then(function($conn) {
    $conn->on('message', function($msg) use ($conn) {
        echo "Received: {$msg}\n";
        $conn->close();
    });

    $conn->send('Hello World!');
}, function ($e) {
    echo "Could not connect: {$e->getMessage()}\n";
});
```

You can transport any kind of data in your message, for example a JSON string that contains something like `{"event":"custom-even","name":"Alice"}` which you could then use to trigger custom logic in your `message` event handler.

I hope this helps :+1:
