### ISSUE TITLE
Is there a way to know the remote port in an Pawl connection?

### ISSUE THREAD

**Issue by carliedu** [ratchetphp/Pawl#127]
After an connection is made with Pawl to an WS server, is there a way to know the remote port (port that is responding on the server).
For example, with netstat | grep 101.17
tcp        0      0 ip-172-31-1-238.s:48916 101.17.94.102:https     ESTABLISHED
I know that the remote port is 48916 and the local port 443.

**Comment by clue** [comment]
The `ws://` scheme defaults to HTTP port `80`, the `wss://` scheme defaults to HTTPS port `443`, unless you explicitly specify a custom port as part of the URL. Does this answer your question?

**Comment by carliedu** [comment]
No. 
The local port (80 or 443) I know, because I'm selecting it with ws: or wss:.
What I would like to get is the remote port, in my example, 48916.
Reason, I have several connections open simultaneously, and I want to know which one I'm specifically dealing with.
