### ISSUE TITLE
underlying connection closed 1006

### ISSUE THREAD

**Issue by hobsRKM** [ratchetphp/Pawl#131]
The socket gets closed with this error after about 3 -4 hours.
I am using the latest version of Pawl.

**Comment by cboden** [comment]
Please provide reproducible steps to replicate this issue. I can't possibly begin to diagnose with this limited amount of information. 

Code 1006 is when the underlying socket is closed without a WebSocket CLOSE Frame. There could be a multitude of reasons for this. Pawl is behaving accordingly.
