### ISSUE TITLE
   Call to undefined function GuzzleHttp\Psr7\uri_for()

### ISSUE THREAD

**Issue by usmanjdn93** [ratchetphp/Pawl#136]
is any one have idea about this error
![Capture](https://user-images.githubusercontent.com/16402690/147138301-dbc0997f-81cf-4837-af36-c6d5964226ad.PNG)

**Comment by cboden** [comment]
Run `composer update`

**Comment by usmanjdn93** [comment]
i did...nothing work

**Comment by usmanjdn93** [comment]
any update on this issue?

**Comment by l-naumann** [comment]
Same problem here. I downgraded to Ratchet 0.4.3 to temporarily fix this.

**Comment by johankitelman** [comment]
bump, the same stuff

**Comment by grasmash** [comment]
This is fixed in [v0.4.1](https://github.com/ratchetphp/Pawl/releases/tag/v0.4.1)

Make sure you require that version. `composer require ratchetphp/Pawl:^0.4.1`
