### ISSUE TITLE
Question - RabbitMq consumer freezing the websocket

### ISSUE THREAD

**Issue by Volmarg** [ratchetphp/Pawl#143]
Hello,

I've got strange case right now where upon starting the `RabbitMq` `consumer` based on the: 
- https://github.com/php-amqplib/RabbitMqBundle

it causes the websocket server to freeze. It will only send messages once I **kill** the consumer, untill then it gets stuck (got no connection errors).

Do You maybe have literaly any idea what can cause this? 
Kinda started hitting the wall right now so I'm looking further - maybe You know something or got literaly any hint for that.

What I already did was:
- changing websocket port,
- updating the package (Yours) to the latest one,

**Comment by Volmarg** [comment]
Solved it.

- **Why was not working**:  no idea,
- **Solution**: dispatching async process to send notification just with `exec`

**Comment by JokubasR** [comment]
I found a better solution after spending some time on this issue. All you need to do is pass Loop while initiating connection and run it afterwards. 

Minimal example:
`
        $loop = Loop::get();
        Client\connect('ws://127.0.0.1', [], [], $loop)->then(
            function (WebSocket $conn) use ($msg) {
                $conn->send($msg);
                $conn->close();
            }
        );
        $loop->run();
`

this way messages to websocket will be sent on every RabbitMQ message consumed

**Comment by sebastianstucke87** [comment]
Sorry, but isn't it kinda inefficient to re-connect on every message while consuming RabbitMQ? I'm currently struggling with the exact same thing. Works like a charm with [this ws-client](https://github.com/Textalk/websocket-php) but not Pawl...

**Comment by 334660335** [comment]
@JokubasR it works, but will memory overflow occur? have some suggestions?
