### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by sacOO7** [ratchetphp/Pawl#155]
I was looking at multiple active issues on the project and seems they are not resolved yet : (
Also, there are some active PRs waiting for review. 
I was curious if there is any active maintainer for the project ?

**Comment by clue** [comment]
> Is this project dead ?

No, it is not 🎉 That said, I agree that this project could use some help, so please help us revive Ratchet and let's give Ratchet the love it deserves! See https://github.com/ratchetphp/Ratchet/issues/1054 for follow-up.
