### ISSUE TITLE
Error with PHP 5.6

### ISSUE THREAD

**Issue by hugohenrique** [ratchetphp/Pawl#17]
I updated my version of php to 5.6 and now I'm getting this error message:

``Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): Peer certificate CN=`*.domain.com' did not match expected CN=`00.000.87.163'```

**Comment by hugohenrique** [comment]
ping @cboden

**Comment by davidwdan** [comment]
I think this is related to https://github.com/reactphp/socket-client/pull/23

**Comment by hugohenrique** [comment]
@davidwdan Just that solves!
