### ISSUE TITLE
Error: Class not found

### ISSUE THREAD

**Issue by aaacckiy** [ratchetphp/Pawl#19]
Hi. I tried to use Pawl but there was a problem in Ratchet\Client\Factory and Ratchet\Client\WebSocket. I can't find any mention about these classes. 
My composer config is 
"require": {
        "cboden/ratchet": "0.3.*",
        "react/socket-client": "0.4.*"
    }
What's the trick? Where can I get required classes?

**Comment by mbonneau** [comment]
Hi @aaacckiy ,

Can you give a little more detail of what you did to install it and maybe the source of the script you are trying to run?

I was able to get this up and running just now using:
```
composer require ratchet/pawl
```

I tested with the script:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$loop = React\EventLoop\Factory::create();
$connector = new Ratchet\Client\Factory($loop);

$connector('ws://echo.websocket.org')->then(function(Ratchet\Client\WebSocket $conn) {
    $conn->on('message', function($msg) {
        echo "Received: {$msg}\n";
    }); 

    $conn->send('Hello World!');
}, function($e) use ($loop) {
    echo "Could not connect: {$e->getMessage()}\n";
    $loop->stop();
}); 

$loop->run();
```
