### ISSUE TITLE
Add a way to decode binary frames

### ISSUE THREAD

**Issue by uniquoooo** [ratchetphp/Pawl#23]
At the moment there is no way to decode binary frames (opcode 2) which is why I had to import the code into my project. Perhaps there should be a way to decode the binary frames?

I am using this code:

```php
if ($this->_message->getOpcode() == Frame::OP_BINARY) {
    $message = zlib_decode($message);
}
```

however, this won't work with all encodings.

**Comment by cboden** [comment]
I haven't used binary frames in practice yet and only understand the differences at the protocol level. I know browsers handle two types, blob and byte stream, but I'm not sure of their practical usages. I'm not sure how to code to handle all scenarios. Do you have any suggestions?

Also you should be able to do this:
```php
$conn->on('message', function(MessageInterface $msg) {
    if ($msg->isBinary()) {
        $payload = zlib_decode($msg->getPayload());
    }
});
```

**Comment by uniquoooo** [comment]
Ah ok, didn't realise in the new version that it passed through the message instead of just the payload. I will give it a go soon.
