### ISSUE TITLE
`close` emitted with React\Stream\Stream

### ISSUE THREAD

**Issue by uniquoooo** [ratchetphp/Pawl#26]
I've had some errors in my application where close is emitted with an instance of React\Stream\Stream, which causes my application to crash when I try to print the close code and reason.

It is because of [this](https://github.com/ratchetphp/Pawl/blob/master/src/WebSocket.php#L113), possibly change it so stream closes emit with `[0, 'PHP stream closed']`?

**Comment by cboden** [comment]
Can you confirm you're using Pawl/0.2.1 via `composer show` please? Can you post a bit of your code where this is happening? Which side is initiating the close command (client/server)? 

The [only spot](https://github.com/ratchetphp/Pawl/blob/master/src/WebSocket.php#L63) `close` is being emitted specifically emits the WebSocket instance; just eyeballing the code I don't see how it could emit an instance of Stream.

**Comment by uniquoooo** [comment]
Sorry for the late reply, completely forgot about this.

[This](https://github.com/ratchetphp/Pawl/blob/master/src/WebSocket.php#L113) seems to be triggering the `_close` function. The ReactPHP Stream package seems to be emitting `close` and it is passing through the Stream class.

Possibly change it to something like:

```php
$stream->on('close', function () {
    $close = $this->_close;
    $close(1006, 'PHP Stream closed');
});
```

**Comment by cboden** [comment]
ah, I see now. You're right. Good call!
