### ISSUE TITLE
connection problem to local addresses

### ISSUE THREAD

**Issue by krekk4** [ratchetphp/Pawl#30]
I can't connect to any address which is resolved by hosts file. It is related to react dns resolver which ignores hosts file and when I run server with ratchet websockets app class I can't connect to server with IP because route is not matched. is there any way to solve this?

**Comment by mbonneau** [comment]
You are correct. React does not currently resolve hosts file mappings: https://github.com/reactphp/dns/issues/10 .

The only way right now is to put the IP address in there or to use a publicly available DNS mapping that resolves to localhost (see http://readme.localtest.me/ - I have not used that but the page says localtest.me will always point to localhost)

**Comment by krekk4** [comment]
Thanks, this did the trick!
