### ISSUE TITLE
HHVM Warning: unable to shutdown socket

### ISSUE THREAD

**Issue by mbonneau** [ratchetphp/Pawl#32]
When running with hhvm I get:

Warning: unable to shutdown socket [107]: Transport endpoint is not connected in /root/phpstuff/Pawl/src/WebSocket.php on line 108

**Comment by mbonneau** [comment]
Could be related to: https://github.com/facebook/hhvm/issues/6978

**Comment by cboden** [comment]
As we're no longer calling the shutdown function ourselves this is now a React issue.

**Comment by clue** [comment]
I suppose the underlying issue has already been worked around in ReactPHP: https://github.com/reactphp/socket/pull/91 :shipit:
