### ISSUE TITLE
How to reopen a closed connection?

### ISSUE THREAD

**Issue by DavidM974** [ratchetphp/Pawl#39]
Hello,
I'm using your lib to do some test on an api and i would like to know how to reopen a connection closed using your exemple on the event close

```php
<?php

    require __DIR__ . '/vendor/autoload.php';

    $loop = React\EventLoop\Factory::create();
    $connector = new Ratchet\Client\Connector($loop);

    $connector('ws://127.0.0.1:9000', ['protocol1', 'subprotocol2'], ['Origin' => 'http://localhost'])
    ->then(function(Ratchet\Client\WebSocket $conn) {
        $conn->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn) {
            echo "Received: {$msg}\n";
            $conn->close();
        });

        $conn->on('close', function($code = null, $reason = null) {
            echo "Connection closed ({$code} - {$reason})\n";
        });

        $conn->send('Hello World!');
    }, function(\Exception $e) use ($loop) {
        echo "Could not connect: {$e->getMessage()}\n";
        $loop->stop();
    });

    $loop->run();
```

How to reopen a connection after this line ` echo "Connection closed ({$code} - {$reason})\n";`

Regards

**Comment by cboden** [comment]
I would recommend creating a new connection when the connection is closed. You'll have to abstract some of your code into re-usable functions and maintain a connection variable. I would also recommend using [RxPHP](https://github.com/ReactiveX/RxPHP) as it makes this kind of behaviour trivial.

**Comment by DavidM974** [comment]
Is it possible to have a small example? i can't find the good way. i tried to put in a function but it's not working.

**Comment by suhuaguo** [comment]
@DavidM974 。hello 。Haveyou solved 【How to reopen a closed connection】 this problem  or give me some idea 。

**Comment by mbonneau** [comment]
@suhuaguo @DavidM974 The connection is only meant to be used once, you have to reestablish the connection.
