### ISSUE TITLE
Support Sub-Protocols

### ISSUE THREAD

**Issue by cboden** [ratchetphp/Pawl#4]

**Comment by adeshpandey** [comment]
is there a  way to disable subprotocol check ?

**Comment by cboden** [comment]
Not on the client side. The server accepts any sub-protocol *requests* from the client and decides how to handle from there.

**Comment by dacoders77** [comment]
What about HYBI protocol support?
https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-14 
I am trying to connect to this C# server

**Comment by cboden** [comment]
HyBi is the code-name for beta version of the WebSocket protocol (now RFC6455); it is not a sub-protocol. Ratchet no longer supports HyBi as it graduated to the RFC with the HTTP version header increment.
