### ISSUE TITLE
Option to disable SSL certificate verification

### ISSUE THREAD

**Issue by jameshilliard** [ratchetphp/Pawl#40]
I'm trying to connect to a websocket server and am getting this error:

```
Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

I should have a valid SSL certificate(it works ok in the browser) however I'm running a non-standard websocket server application which may have issues with the full chain.
I'm trying to disable SSL certificate verification for testing but I'm not seeing an obvious way to do that.

**Comment by cboden** [comment]
The [third parameter](https://github.com/ratchetphp/Pawl/blob/master/src/Connector.php#L20) of the  Connector class accepts an associative array of [SSL context options](http://php.net/manual/en/context.ssl.php).
