### ISSUE TITLE
Pass custom dns resolver

### ISSUE THREAD

**Issue by mougrim** [ratchetphp/Pawl#42]
It will be great, if I can pass custom dns resolver to `\Ratchet\Client\connect` (and pass it to `\Ratchet\Client\Connector` construct).

**Comment by mougrim** [comment]
Possibility to use `\React\SocketClient\TcpConnector` instead of `\React\SocketClient\DnsConnector` would be great to.

**Comment by cboden** [comment]
The connect function is meant to simplify 90% of use cases by having a minimal API. The Connector class allows more customization, including a custom DNS Resolver, which is what you should use if that's required. 

I don't quite follow your second comment about the Connectors?

**Comment by mougrim** [comment]
@cboden after half a year, I'm not sure, what I did mean.
But I think, it's about [src/Connector.php](https://github.com/ratchetphp/Pawl/blob/master/src/Connector.php):
```php
$this->_connector       = new SocketConnector($loop, $resolver);
```
SocketConnector is deprecated and \React\SocketClient\DnsConnector's wrapper.
So, I think it would better have possibility to provide connector. If it isn't passed, use  \React\SocketClient\DnsConnector.

So, ok, I can create my own function create, but I can't provide custom connector to \Ratchet\Client\Connector::__construct().
Instead of parameter Resolver $resolver = null we can use connector parameter.

**Comment by mougrim** [comment]
> The connect function is meant to simplify 90% of use cases by having a minimal API. The Connector class allows more customization, including a custom DNS Resolver, which is what you should use if that's required.
Also it would great to add doc to function connect about it.

**Comment by mbonneau** [comment]
+1 for adding a connector argument to the constructor instead of the resolver.

**Comment by cboden** [comment]
With the release of v0.3 you can now customize DNS information on the Connector class via React's Connector class. See the example at the bottom of the README for an example.
