### ISSUE TITLE
react/socket-client

### ISSUE THREAD

**Issue by ikovalyov** [ratchetphp/Pawl#46]
Any way to update composer to require 0.7 version? Or even require https://github.com/reactphp/socket instead?

**Comment by cboden** [comment]
Yup, this is something that should be done. I'll look into it in the next couple weeks.

**Comment by mbonneau** [comment]
See #56

**Comment by cboden** [comment]
Done! Thanks @mbonneau!!! v0.3 has been released with a slight API break that now uses the latest version of React Socket.
