### ISSUE TITLE
Unable to complete SSL/TLS handshake

### ISSUE THREAD

**Issue by fudepita** [ratchetphp/Pawl#49]
Hello. I'm trying to avoid SSL error, but who understands why it does not work?

Error:
---
Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
---

Code Part:
---
$url_twoway_list = "wss://public.bitpoint.co.jp/bpj-api/twoWay?access_token=" . $access_token;
$loop = React\EventLoop\Factory::create();
$connector = new Ratchet\Client\Connector($loop);
$connector($url_twoway_list,['tls'],['verify_peer' => false,'verify_peer_name' => false])->then(function(Ratchet\Client\WebSocket $conn) {
---

**Comment by user4B1D** [comment]
Maybe try providing a cafile?

**Comment by fudepita** [comment]
thanks!　I avoided it, but it does not work.
Is not it compatible with SockJS?

---
Could not connect: HTTP/1.1 200 200
Date: Fri, 23 Jun 2017 07:28:32 GMT
Server: Apache
Access-Control-Allow-Origin: https://public.bitpoint.co.jp
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: text/plain;charset=UTF-8
Content-Length: 19
Set-Cookie: BIGipServerpool_172.17.1.113_443=1862341292.20480.0000; path=/

Welcome to SockJS!

**Comment by mbonneau** [comment]
@fudepita - It looks like you should be passing the `secureContext` to the constructor, not the invocation:

https://github.com/ratchetphp/Pawl/blob/55256f590ab457fc9da57aa3f88e2edb5a2386c1/src/Connector.php#L20

**Comment by mbonneau** [comment]
@fudepita - I am closing this issue. Please let us know if the previous solution worked.
