### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by shtse8** [ratchetphp/Pawl#51]
I want to connect to a websocket using PHP, but a segmentation fault is thrown.

Code:
```
\Ratchet\Client\connect('wss://be.huobi.com/ws');
```

Result:
```
Segmentation Fault(Core Dumped)
```

Environment:
1. Libevent 2.1.8
2. PHP 7.1

**Comment by clue** [comment]
It looks like you're using an unsupported beta of ext-libevent here? See also https://github.com/reactphp/event-loop/pull/62 for more details.

**Comment by shtse8** [comment]
Thanks for your help. I have read that post before. But I still don't understand how I should fix it. Which libevent or any other event extensions should I install. I have followed some guild lines from google and compile the latest version of libevent which supported php 7.1 other people said. But still throwing SF.

**Comment by clue** [comment]
The beta of ext-libevent you're using is currently bugged, make sure to let the author of said guides lines know :+1: 

In the meantime, you may want to check out the "event" extension. We've seen reports of people successfully using this on PHP7, see also https://github.com/reactphp/event-loop/issues/55#issuecomment-271234568.

**Comment by shtse8** [comment]
Thanks very much! It works great now.
