### ISSUE TITLE
Connecting to WSS: Unable to complete SSL/TLS handshake

### ISSUE THREAD

**Issue by JimmyPruitt** [ratchetphp/Pawl#53]
I have a Websocket server that is running behind Apache that I'm able to connect to using Chrome, Safari, and Telnet just fine. However, when attempting to connect to that same server from PHP using Pawl, it's throwing an exception during the handshake: 

`Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): Peer certificate CN='*.foo.bar' did not match expected CN='local.blah.foo.bar'`.

Here's my client code:

```
\Ratchet\Client\connect('wss://' . WEBSOCKET_SERVER_HOST . ':' . WEBSOCKET_SERVER_PORT)
    ->then(
          function ($conn) use ($message) {
              $conn->send($message);
          },
          function ($e) {
              echo $e;
          }
    );
```

**Comment by cboden** [comment]
Take a look at previous [issues about ssl](https://github.com/ratchetphp/Pawl/search?q=ssl&type=Issues&utf8=✓). It looks like you're using a self signed certificate? In that case you need to pass [SSL context options](http://php.net/manual/en/context.ssl.php) to the Connector.

**Comment by JimmyPruitt** [comment]
Does that mean I would have to instantiate the `Connector` myself, or would this be in the third parameter to `connect()`?

**Comment by mbonneau** [comment]
I didn't see the follow up question - reopening...

**Comment by mbonneau** [comment]
@JimmyPruitt - On your follow-up question - do you know if the name is able to be resolved? By default the resolver in Pawl uses `8.8.8.8`.

**Comment by clue** [comment]
> Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): Peer certificate CN='*.foo.bar' did not match expected CN='local.blah.foo.bar'.

This error looks correct to me, as wildcard SSL certificates should only work one level below the root domain, perhaps https://stackoverflow.com/questions/2115611/wildcard-ssl-on-sub-subdomain could help here?

Other than that, you may also pass the `peer_name` context option to set the expected peer name for your remote host. This parameter should have preference over the implicit domain name from the connection URI.

**Comment by mbonneau** [comment]
Closing this issue - please feel free to comment if your issue is not fixed.

**Comment by Aymkdn** [comment]
Since 2017, the way to do it changed, and I think it should now be:
```php
require __DIR__ . '/vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();
$connector = new \React\Socket\Connector($loop, [
  'timeout' => 20,
  'tls' => [ // here we define the SSL Context options (https://www.php.net/manual/en/context.ssl.php)
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true
  ]
]);
$wsClient = new \Ratchet\Client\Connector($loop, $connector);
$wsClient('wss://IP:PORT')->then(function($conn) {
    $conn->on('message', function($msg) use ($conn) {
        echo "Received: {$msg}\n";
        $conn->close();
    });

    $conn->send('Hello World!');
}, function ($e) {
    echo "Could not connect: {$e->getMessage()}\n";
});

$loop->run();
```
