### ISSUE TITLE
How Check if server is online

### ISSUE THREAD

**Issue by FelipeVargas86** [ratchetphp/Pawl#55]
How check if server is online or offline??? why function exception doesn't work

**Comment by mbonneau** [comment]
@FelipeVargas86  - could you please provide a bit more info? If you are getting an exception, can you post that here?

**Comment by CyanoFresh** [comment]
maybe related to #41

**Comment by cboden** [comment]
@FelipeVargas86 Can you test with v0.3 with a timeout option in the connector? (see bottom of the README for an example). With that are you still having a problem?
