### ISSUE TITLE
Is `onOpen` possible?

### ISSUE THREAD

**Issue by enygma** [ratchetphp/Pawl#63]
I'm trying to look through the source to see if there's a way to have an `on` handler for "open" but all I'm seeing are `close` and `message`. Is there a way I'm missing to be able to fire an event on the opening of the connection and before the first message comes in?

**Comment by cboden** [comment]
When the [WebSocket class](https://github.com/ratchetphp/Pawl/blob/master/src/WebSocket.php) is instantiated by the connector, resolving the promise, and returned inside your `then` function the connection is open.

**Comment by cboden** [comment]
Closing as it looks like you got it [figured out](https://github.com/psecio/dbot) 😀 👍
