### ISSUE TITLE
Wamp2 error

### ISSUE THREAD

**Issue by sentiasa** [ratchetphp/Pawl#64]
I am pretty new to websockets and I tried making a websocket connection with poloniex. This is what I have run:

```php
$loop = Factory::create();
        $connector = new Connector($loop);

        $connector('wss://api.poloniex.com')
            ->then(function(WebSocket $conn) {
                $conn->send('{"event": "subscribe","channel":"ticker","pair": "BTC_ETH"}');

                $conn->on('message', function(MessageInterface $msg) use ($conn) {
                    var_dump($msg);
                });
            }, function(\Exception $e) use ($loop) {
                /** hard error */
                echo "Could not connect: {$e->getMessage()}\n";
                $loop->stop();
            });

        $loop->run();
```

But I received error:
> Could not connect: HTTP/1.1 400 This server only speaks WebSocket subprotocols wamp.2.cbor.batched, wamp.2.cbor, wamp.2.msgpack.batched, wamp.2.msgpack, wamp.2.json.batched, wamp.2.json

I also tried `$connector('wss://api.poloniex.com', ['wamp'])` and `$connector('wss://api.poloniex.com', ['wamp2'])` but same error persists

**Comment by mbonneau** [comment]
Looks like that server speaks WAMPv2 - see https://github.com/voryx/Thruway or https://github.com/voryx/RxThruwayClient for WAMPv2 PHP clients.

**Comment by mbonneau** [comment]
@sentiasa 

I tried this out with RxThruwayClient - here is the code to maybe save you some time getting it going:
```php
<?php

use Rx\Thruway\Client;
use Thruway\Message\EventMessage;

require __DIR__ . '/vendor/autoload.php';

$client = new Client('wss://api.poloniex.com', 'realm1');

$client->topic('ticker')
    ->map(function (EventMessage $message) {
        $names = ['currencyPair', 'last', 'lowestAsk', 'highestBid', 'percentChange', 'baseVolume', 'quoteVolume', 'isFrozen', '24hrHigh', '24hrLow'];
        return array_combine($names, $message->getArguments());
    })
    ->subscribe('print_r');
```
