### ISSUE TITLE
TCP connection

### ISSUE THREAD

**Issue by suhuaguo** [ratchetphp/Pawl#65]
hello . The Pawl support persistent TCP ? but I cannot seek out this code ?

**Comment by cboden** [comment]
I don't believe ReactPHP (which powers Pawl) has support for persistent TCP connections. What is the use case you require this for?

**Comment by suhuaguo** [comment]
consume MQ(Kafka  RocketMQ) message 。so i try it 。Pawl can support persistent TCP

**Comment by clue** [comment]
I think the word "persistent" may be a bit misleading when using ReactPHP. If you're using ReactPHP, then everything will be "persistent" until you kill your process or explicitly close any stream. This means that Pawl will use "persistent TCP/IP connections" by default.

Does this help?
