### ISSUE TITLE
  asynchronous WebSocket client  

### ISSUE THREAD

**Issue by suhuaguo** [ratchetphp/Pawl#68]
I use Pawl  ，but it is not asynchronous 。it is really asynchronous ?

**Comment by mbonneau** [comment]
Yes - it is async - check out the examples in the README for more info: https://github.com/ratchetphp/Pawl#example or read up on ReactPHP at https://github.com/reactphp/react/wiki/FAQ.

**Comment by TaylorHawkes** [comment]
@mbonneau, can you clarify in what way it is async? In below code, I would expect If I received 3 messages within the same second, all three messages would complete in 60 seconds, but it looks like they process one after another... ie: 180 seconds.  What would you expect the behavior to be?
 
$conn->on('message', function($msg) use ($conn) {
   sleep(60); 
  echo "done";
});

**Comment by TaylorHawkes** [comment]
To answer myself, I think I now get the thrust... The communication ie async. i.e "send()" does not wait for response. I was hoping the code would be async as well....
