### ISSUE TITLE
why is connect function always executed as last instruction?

### ISSUE THREAD

**Issue by sangio90** [ratchetphp/Pawl#69]
Hello,
 I'm trying to send multiple WS messages during a long procedure (30 to 60 seconds).
Calls to _connect_ function were put in different places but what I notice is that they are all executed as last instructions of my procedure, so what I get is a bunch of messages sent at the end of the procedure.

Is it supposed to work this way? Should I use Threads to avoid it?

Thanks!

**Comment by sangio90** [comment]
I went into more depth to find out that the problem was in the send/close method.

They are called synchronously, but the stream is passed to the server asynchronously and in my case they are all waiting for my procedure to complete (don't know why).

The only way around was to execute the rest of my procedure in a callback called on $conn event "close".

e.g.

```
//Step 1, 2, 3 of my procedures
connect('ws://localhost:12345')->then(function($conn) {
    $conn->send('step 1,2, 3 completed');
    $conn->close();
    
});

$conn->on('close', function() {
   //Step 4,5
});
```

Anyone of you found a better solution?

**Comment by clue** [comment]
> […] a long procedure (30 to 60 seconds).

ReactPHP works under the assumption that the loop must not be blocked. If you block the loop for this period of time, you're going to run into problems, see also https://github.com/reactphp/react/wiki/FAQ.

This is a pretty common problem. As an alternative, I would suggest moving these kind of things off to a worker queue.

**Comment by sangio90** [comment]
The strange thing here is that I was expecting the ->send function to block the rest of the execution, instead what I got was a super fast ->send and ->close call, (that did nothing) and then the rest of my steps (4,5 which where just after the ->close call), and only then the ->send call would be really executed. Is it right?

What I want to achieve is a batch script which informs the WS Server (and the clients) of its progression, so on each step I want to send a message to the server telling it "I've done step X".

**Comment by clue** [comment]
Both `send()` and `close()` are async. And so should be your "long procedure". Maybe use react/child-process to spawn this in a separate process and use STDIN/STDOUT to send "progress" messages?

**Comment by sangio90** [comment]
I'll try the child-process and let you know. My "progress" messages should be sent to the client which should reload a grid whenever some of the steps are completed, so I cannot use stdin/out. I'm not sure if there are best practices on how to handle these problems.

**Comment by clue** [comment]
Here's some pseudo code to get you started :+1: 

```
$process = new Process('ping google.com');
$process->start($loop);
$process->stdout->on('data', function ($chunk) use ($conn) {
    $conn->send($chunk);
});
```

**Comment by cboden** [comment]
In addition to what Christian has said part of the reason nothing happens until the end of your procedure is that when using nonblocking I/O in PHP the code is lazy and doesn't execute until the event loop starts running, which if you're using the "simple" example from the README, happens [at the end of the process](https://github.com/ratchetphp/Pawl/blob/master/src/functions.php#L19-L20).

**Comment by sangio90** [comment]
So in the end I should split my procedure into multiple Commands, at the end of which I send a websocket message and call php-cli process to execute the next step, right?

**Comment by clue** [comment]
```
$process = new Process('php procedure.php');
$process->start($loop);
$process->stdout->on('data', function ($chunk) use ($conn) {
    $conn->send($chunk);
});
```

```
# prodecure.php
<?php

echo "hello\n";

sleep(2);
echo "1\n";

sleep(10);
echo "2\n";

sleep(2);
echo "3\n";

sleep(2);
echo "done\n";

**Comment by sangio90** [comment]
Thanks guys!
