### ISSUE TITLE
Could not connect: Server did not respond with an expected Sec-WebSocket-Protocol 

### ISSUE THREAD

**Issue by mrshidashrf** [ratchetphp/Pawl#74]
Hi, I m using this package or facing this error. please help me to slove this issue

**Comment by mbonneau** [comment]
@mrshidashrf Can you please provide more information? What are you connecting to? What subprotocol is it running? Can you post your code?

**Comment by mrshidashrf** [comment]
Hi, i m trying to connect crypto exchange wss api, url ( 'wss://www.bitmex.com/realtime?subscribe=instrument,orderBook:XBTUSD ) but getting this which is in question tilte 


`require __DIR__ . '/vendor/autoload.php';
    $loop = React\EventLoop\Factory::create();
    $reactConnector = new React\Socket\Connector($loop, [
        'dns' => '8.8.8.8',
        'timeout' => 10
    ]);
    $connector = new Ratchet\Client\Connector($loop, $reactConnector);
    $connector('wss://www.bitmex.com/realtime?subscribe=instrument,orderBook:XBTUSD', ['protocol1', 'subprotocol2'], ['Origin' => 'http://localhost'])
    ->then(function(Ratchet\Client\WebSocket $conn) {
        $conn->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn) {
            echo "Received :- ".$msg->__toString(5).'<br/>';
            $conn->close();
        });
 
        $conn->on('close', function($code = null, $reason = null) {
            echo "Connection closed ({$code} - {$reason})\n";
        });
        

        
        $conn->send('Hello World!');
    }, function(\Exception $e) use ($loop) {
        echo "Could not connect: {$e->getMessage()}\n";
        $loop->stop();
    });

    $loop->run();`

**Comment by mbonneau** [comment]
@mrshidashrf Drop all the arguments to `$connector` except for the URL. You are specifying subprotocols which is unnecessary for the bitmex API. (Also remove the `$conn->close` if you want the connection to remain open.

**Comment by parmonov98** [comment]
> @mbonneau I m trying to connect with crypto exchange wss api. i m just put api url in your code and getting this error which is mentioned on question title
> 
> ```
>     require __DIR__ . '/vendor/autoload.php';
>     $loop = React\EventLoop\Factory::create();
>     $reactConnector = new React\Socket\Connector($loop, [
>         'dns' => '8.8.8.8',
>         'timeout' => 10
>     ]);
>     $connector = new Ratchet\Client\Connector($loop, $reactConnector);
>     $connector('wss://www.bitmex.com/realtime?subscribe=instrument,orderBook:XBTUSD', ['protocol1', 'subprotocol2'], ['Origin' => 'http://localhost'])
>     ->then(function(Ratchet\Client\WebSocket $conn) {
>         $conn->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn) {
>             echo "Received :- ".$msg->__toString();
>             $conn->close();
>         });
>  
>         $conn->on('close', function($code = null, $reason = null) {
>             echo "Connection closed ({$code} - {$reason})\n";
>         });
>         
> 
>         
>         $conn->send('Hello World!');
>     }, function(\Exception $e) use ($loop) {
>         echo "Could not connect: {$e->getMessage()}\n";
>         $loop->stop();
>     });
> 
>     $loop->run();
> ```

Hello, dude! How could you manage to get stream data from bitmex API?  
I wrote the same code, corrected as  **mbonneau** but when I open the file on browser. it is stuck on reload proccess. what Do I need to do to get the stream data?
I tried the wss api with browser that stream data keeps coming from server after connection to websocket. but in php it is kinda confusing. (actually it is my first time to use websocket in php).

**Comment by parmonov98** [comment]
> @mrshidashrf Drop all the arguments to `$connector` except for the URL. You are specifying subprotocols which is unnecessary for the bitmex API. (Also remove the `$conn->close` if you want the connection to remain open.

hi, Matt Bonneau . Can you give more details on how to work with web sockets? 
or direct me to the right direction?
