### ISSUE TITLE
Question: How to set Websocket client class using PAWL

### ISSUE THREAD

**Issue by oacApps** [ratchetphp/Pawl#75]
Hi @cboden @mbonneau 
I just installed and configure RATCHET server and it is working 100% with my JavaScript (Browser) client. So I was looking for php client and came across this PAWL. This is looking great but I am failing to meet my requirements. I believe It does provide what I need and I am missing something. What I want to do is 
"Write a class, which may have some method like 'ConnectToServer', 'sendMessage', 'disconnectServer.' "
So first I will connect to the server, then send message 1, message 2, message 3 ....... message N. Once I am done I will disconnect with the server.

Is there any way I can implement this. 

I appreciate your help.

**Comment by cboden** [comment]
Yes, Pawl should meet your requirement. You should be able to do that from the example on the README.
