### ISSUE TITLE
Connect and send synchronously

### ISSUE THREAD

**Issue by rudiedirkx** [ratchetphp/Pawl#76]
I want to connect and send synchronously. I'd like to use Pawl, because I'm also using Ratchet somewhere else in the same project.

So no promises, no shutdown functions. Just connect and send, and use the response (IF it worked, no incoming data).

Is that possible, or is this only promise based? Or can I have synchronous promises?

**Comment by rudiedirkx** [comment]
This is synchronous:

```
$loop = ReactFactory::create();

$connector = new Connector($loop);
$connection = $connector('wss://example.com/ws');
$connection->then(function(WebSocket $conn) {
	echo "Connected. Sending message...\n";
	$conn->send((string) rand());
	echo "Sent message\n";
	$conn->close();
}, function (DomainException $ex) {
	echo $ex->getMessage(};
});

$loop->run();
```

but not very pretty. Is there a provided wrapper or do I wrap it myself?

**Comment by rudiedirkx** [comment]
Just to be extra verbose, what I'd love is something like:

```
$ws = WebSocket::connect(''wss://example.com/ws'');
$ws->send('bla');
$ws->close();
```

or something. Without promises and closures.

Is there a synchronous non-promise `Connector`?

**Comment by cboden** [comment]
Pawl wasn't created with synchronous communication in mind because the WebSocket specification is bi-directional. You don't need to use the shutdown feature if you use your own React loop. 

You can try clue/php-block-react if you want to use a coding style that doesn't require callbacks.

**Comment by rudiedirkx** [comment]
`clue/php-block-react` is JS' `async/await`! That is very cool. Still event loop bound though. I know enough. Thanks.

**Comment by yepes** [comment]
can anybody provide an example for this?

**Comment by metaer** [comment]
I think for sending message synchronously it's better to use https://github.com/Textalk/websocket-php
