### ISSUE TITLE
Is the communication between two Websockets Clients possible?

### ISSUE THREAD

**Issue by mazetuski** [ratchetphp/Pawl#77]
I have 2 clients, one of them obtains data from an external server (this data I need to pass them to my websocket server with ratchet).
The other websocket client would serve to connect to my server with ratchet and pass the data obtained by the first websocket client.
Is there any way to get messages from one websocket client in the other websocket client?

**Comment by clue** [comment]
Absolutely! Here's the gist:

```php
$conn1->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn2) {
    echo "forwarding $msg\n";
    $conn2->send($msg);
});
```

**Comment by ASK-Lee** [comment]
> Absolutely! Here's the gist:
> 
> ```
> $conn1->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn2) {
>     echo "forwarding $msg\n";
>     $conn2->send($msg);
> });
> ```

@clue Could you give a more detailed example? I don't know how to get $conn1 and $conn2, code as below is incorrect.
```
$promise = new \React\Promise\Deferred();
$conn1 = $promise->resolve(\Ratchet\Client\connect($remoteHost));
$conn2 = $promise->resolve(\Ratchet\Client\connect($localHost));
```
