### ISSUE TITLE
Unable to write to stream: fwrite(): send of XXX bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by Dju33** [ratchetphp/Pawl#79]
Hi everyone,

I have this error with my websocket :

> Unable to write to stream: fwrite(): send of 243 bytes failed with errno=32 Broken pipe

this appends a lot and I don't know how to solve it...I googled it but find nothing...so I really need your help.

Here my version :

```
ratchet/pawl   v0.3.1
ratchet/rfc6455  v0.2.3
react/cache  v0.4.2
react/dns v0.4.13
react/event-loop  v0.4.3
react/promise v2.5.1
react/promise-timer  v1.2.1
react/socket  v0.8.10
react/stream  v0.7.7 
```

PHP 7.1.11 (cli) (built: Oct 27 2017 14:45:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by mbonneau** [comment]
Answered here: https://github.com/reactphp/stream/issues/135
