### ISSUE TITLE
How to use with protobuf?

### ISSUE THREAD

**Issue by skecskes** [ratchetphp/Pawl#83]
Hi,

I'm trying to send messages to websocket using your ws client library. The websocket is using Google protobuf standard. Basicaly from *.proto file you are able to understand contract and create objects with required/optional values. I have working example of ws communication provided by their side in Javascript.  

I'm constructing message in php, which looks very same as js example. It should be an array of int values (0-255) where each int represents character. In php I'm receiving error message that 
`#�Request error: unknown message`.

Is your wrapper already encoding characters? Is there any other issue why your wrapper doesn't work with protobuf standard? Am I missing something? 

![js-example](https://user-images.githubusercontent.com/3411329/47617938-fa256500-dac4-11e8-95a0-5d272066b28e.png)

![php-example](https://user-images.githubusercontent.com/3411329/47617942-03163680-dac5-11e8-9201-9acd3a5e7c28.png)

**Comment by mbonneau** [comment]
@skecskes Protobuf is a binary protocol. In order to send binary, you need to construct the message before calling `send`:
```php
$myBinaryMessage = new Frame($binaryPayload, true, Frame::OP_BINARY);
$conn->send($myBinaryMessage);
```
