### ISSUE TITLE
Receiving incomplete message after close

### ISSUE THREAD

**Issue by CharlotteDunois** [ratchetphp/Pawl#94]
Today an issue opened in my library has raised my eyebrows. This issue here is more a question than a bug report.

Someone reported an error about a call to close on null (although that has never happened before), due to that property being null (which should always be the websocket connection), it indicates that the websocket was closed prior to emitting the message event.

The property is only set to null in the close event handler and as such, when receiving a message the assumption is made that it would never be invoked after a close was indicated.

But due to the exception and the location of the exception source, the exception suggests that the close occurred while receiving a message and the message event was emitted with an incomplete message. When trying to zlib decode the data, it unable to decode it and thus went into the logic branch to close the websocket (which failed because the property was null).

Is this a scenario that should even happen at all? I'm under the impression that when a close occurres, that there should never be a message event after it. Is this therefore a side effect in this library (maybe the RFC6455 one?) that should be fixed, or is this something that library should should protect themself against?

The original issue report (for something completely unrelated to websocket, but included that exception (scroll to the end of the post)) is [here](https://github.com/CharlotteDunois/Yasmin/issues/96). The relevant code is [here](https://github.com/CharlotteDunois/Yasmin/blob/1534b4ed9df3af205a43a73d290ce26a5772e30c/src/WebSocket/WSConnection.php#L619-L635).

**Comment by mbonneau** [comment]
@CharlotteDunois Once a `close` or `error` event happens, there should be no more events emitted from the `WebSocket`. When I get a chance I will dig into it a little and see if there may be an issue. If you are able to reproduce, that would be helpful also.

It may be worth removing all listeners from the `WebSocket` once `close` is emitted just as an extra guarantee. Would rather locate why it may be happening though.
