### ISSUE TITLE
How to throw in rejected connect handler

### ISSUE THREAD

**Issue by edolix** [ratchetphp/Pawl#95]
Hello,

i'm not able to `throw` inside the rejected callback of `\Ratchet\Client\connect`.

```php
\Ratchet\Client\connect('wss://not-exists.fake')->then(function($conn) {
  echo "connected!";
}, function ($e) {
  echo $e->getMessage();
  throw $e;
});
```

I also tried:

- `->done()` instead of `->then()` 
- without passing the error handler at all

Oddly, if i try with wifi turned off (`Network is unreachable` error), i get the Exception and i can throw as well... but with a wrong domain, the reject handler fails silently.

**Comment by cboden** [comment]
What are you trying to achieve? Throwing inside the rejection will just change the stack trace of the Promise.

**Comment by edolix** [comment]
I changed my implementation using `Ratchet\Client\Connector` directly instead of `\Ratchet\Client\connect` but i think the issue was that i did not "return" the Promise.

Going to close this, thanks @cboden 👍

**Comment by seewhy17** [comment]
> Connector

@edolix would you mind explaining what you meant by **I did not "return" the Promise.**
I have a similar issue and I cant seem to throw an exception

**Comment by edolix** [comment]
@seewhy17 IIRC: i meant to actually `return` the _Promise_ to bubble up the error.

Taking my example from above:

```php
$promise = \Ratchet\Client\connect('wss://not-exists.fake');

return $promise->then(function($conn) {
  echo "connected!";
}, function ($e) {
  echo $e->getMessage();
  throw $e;
});
```

Might be just that but, as mentioned in the prev comment, i then switched to `Ratchet\Client\Connector` so i'm not sure if `return` is the fix 👍  Let me know how it goes!

**Comment by seewhy17** [comment]
@edolix Thanks for your reply. still could not get it work with both implementations. I am working on a laravel project.
## Class Example
```

<?php

namespace App\Services;

use App\Models\Transaction;
use App\Exceptions\SomeCustomException;

class SomeActionService
{
  private $connection;
  private $transaction;
  public $error_message;

  protected static $instance = null;

  public static function run($transaction)
  {
      if ( is_null ( self::$instance ) ) {
          self::$instance = new self($transaction);
      }

      return self::$instance;
  }


  public function __construct(Transaction $transaction) {
    $this->connection = \Ratchet\Client\connect(config('~.url') . '?app_id=' . config('~.app_id'));
    $this->transaction = $transaction;
  }

  public function authorize($callback) {

    return $this->connection->then(function($connection) use ($callback) {
      $connection->send(json_encode([
        'authorize' => config('~.token')
      ]));
      $connection->on('message', function($message) use($connection, $callback) {
        $response = json_decode($message, false);
        
        if ( $response->msg_type === 'authorize' ) {
          call_user_func($callback, $connection);
        }

        if (isset($response->error)) {
            $connection->close();
            throw new SomeCustomException($response->error->message);
        }
        
        if ($response->msg_type === 'balance') {
          $connection->close();
          echo "Balance: {$response->balance->balance}\r\n";

        }
        });
    }, function(\Exception $exception) {
      throw new SomeCustomException($exception->getMessage());

    });
  }


  public function balance() {
    return $this->authorize(function($connection) {
          $connection->send(...);
      });
  }


}

```


## Using the above class
```
$transaction = Transaction::find(1);
SomeActionService::run($transaction)->balance();

```
None of the exceptions are thrown.

Currently trying [amphp](https://github.com/amphp/websocket-client)

**Comment by edolix** [comment]
For context regarding the "return the Promise" i said above: https://reactphp.org/promise/#done-vs-then 

Maybe @cboden has some additional ideas for your class example 👍

**Comment by cboden** [comment]
@seewhy17 You're trying to alter an asynchronous paradigm to a procedural paradigm; square peg into a round hole. 

The connection is happening inside a Promise, so if it throws it rejects the Promise. You either need to alter your flow to work to this asynchronous paradigm or unwrap it by using something like [clue/reactphp-block](https://github.com/clue/reactphp-block) by @clue
