### ISSUE TITLE
Unable to send json via php's json_encode

### ISSUE THREAD

**Issue by fabian-hilft** [ratchetphp/Pawl#96]
My problem is that I can't send json when I use json_encode. It sends just _null_.

`$array = array(
	"test" => "v1",
	"test2" => "v2"
);`

`$conn->send(json_encode($array));`

Anyone with a similar issue?

**Comment by clue** [comment]
`json_encode()` returns a `string` on success and `null` on failure. It looks like your `$array` contains data that can not be represented as a JSON text, for example if it doesn't use UTF-8 encoding, contains binary data etc.

This means it's likely an issue with your data and not with this library. If the function successfully returns a `string`, then I see no reason to assume that you wouldn't be able to send this value. You can assign the result of this function to a variable and check `json_last_error()`.

**Comment by fabian-hilft** [comment]
Thanks for the tip. I checked this and json_last_error() says 0/JSON_ERROR_NONE
