### ISSUE TITLE
OP_PING response.

### ISSUE THREAD

**Issue by toleRB** [ratchetphp/Pawl#99]
Should I expect a response from:
```php
$loop->addPeriodicTimer(5, function () use ($ws, $symbol) {
                    if (time() - $this->symbolsTimeOut[$symbol] > 5) {
                        echo "Inactive for more than 5 seconds\n";
                        print_r($ws->send(new \Ratchet\RFC6455\Messaging\Frame('', true, \Ratchet\RFC6455\Messaging\Frame::OP_PING)));
                    }
                });
```
I get the echo output but nothing from sending the ping and the server is supposed to send a pong back.

**Comment by mbonneau** [comment]
Sending the ping does not give any response. You would need to listen to the PONG event that is emitted here:
https://github.com/ratchetphp/Pawl/blob/b06df345c373443a4cbb026da245d54b92faf518/src/WebSocket.php#L94

**Comment by toleRB** [comment]
Thanks for your answer @mbonneau , but I didn't create the websocket server, I'm connecting to an external websocket server and I need to know if the connection is still active. The server in its documentation says that it responds with a pong:

> After receiving each message, set a timer a duration of 5 seconds.
> If any message is received before that timer fires, restart the timer.
> When the timer fires (no messages received in 5 seconds), send a raw ping frame (if supported) or the literal string 'ping'.
> Expect a raw pong frame or the literal string 'pong' in response. If this is not received within 5 seconds, throw an error or reconnect.

Is there any way to check this?

Thanks in advance.

**Comment by hurdos** [comment]
@toleRB Just subscribe on PONG event.
```php

$loop = \React\EventLoop\Factory::create();
$reactConnector = new \React\Socket\Connector($loop, [
    'dns' => '8.8.8.8',
    'timeout' => 10
]);
$connector = new \Ratchet\Client\Connector($loop, $reactConnector);

$url = 'wss://echo.websocket.org/';
$connector($url)
    ->then(function(WebSocket $conn) use ($loop) {
        echo date('Y-m-d H:i:s T') . ' Connected' . PHP_EOL;

        // Receiving PONG
        $conn->on('pong', function (FrameInterface $frame) {
            echo date('Y-m-d H:i:s T') . ' PONG:' . PHP_EOL;
        });

        // Send PING
        $ping = new Frame('', true, Frame::OP_PING);
        echo date('Y-m-d H:i:s T') . ' PING:' . PHP_EOL;
        $conn->send($ping);
    }, function(\Exception $e) use ($loop) {
        echo "Could not connect: {$e->getMessage()}" . PHP_EOL;
        echo $e->getTraceAsString() . PHP_EOL;
        $loop->stop();
    });
```
